#!/bin/bash

NAME="zajecia"                                      # Name of the application
DJANGODIR=C:\projects\zajecia\zajecia                              # Django project directory
# najpierw musimy zrobich w tym folderze `touch gunicorn.sock`
SOCKFILE=C:\projects\zajecia\zajecia\gunicorn.sock                  # we will communicte using this unix socket
USER=zjecia                                           # the user to run as
GROUP=webapps                                       # the group to run as
NUM_WORKERS=5                                       # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=zajecia.settings            # which settings file should Django use
DJANGO_WSGI_MODULE=zajecia.wsgi                    # WSGI module name
echo "Starting $NAME as `whoami`"
# Activate the virtual environment
cd $DJANGODIR
# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR
# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --bind=unix:$SOCKFILE \
  --log-level=debug \
  --log-file=-
