# Generated by Django 3.0 on 2020-05-24 10:56

from django.db import migrations, models


def fillData(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Car = apps.get_model("fleet", "Car")
    Car.objects.bulk_create([
        Car(brand="VOLVO", year=2012, petrol=2, model="XC60"),
        Car(brand="Suzuki", year=2012, petrol=1, model="Swift"),
    ])


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='Brand', max_length=12)),
                ('petrol', models.IntegerField(choices=[(1, 'LPG'), (2, 'DIESEL'), (3, 'ELECTRIC'), (4, 'HYBRID')], default=1)),
                ('model', models.CharField(max_length=32)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load', models.IntegerField()),
            ],
        ),
        migrations.RunPython(fillData)
    ]
