# Generated by Django 3.0 on 2020-05-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='doors',
            field=models.IntegerField(default=5),
        ),
    ]
