# Generated by Django 3.0 on 2020-06-07 11:07

from django.db import migrations, models
import fleet.validators


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_car_doors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Pojazd', 'verbose_name_plural': 'Pojazdy'},
        ),
        migrations.AddField(
            model_name='car',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(default='Brand', max_length=12, validators=[fleet.validators.first_brand_letter_uppercase]),
        ),
    ]
