# Generated by Django 3.0 on 2020-06-21 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_auto_20200607_1307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'permissions': [('rent_car', 'Access to renting car')], 'verbose_name': 'Pojazd', 'verbose_name_plural': 'Pojazdy'},
        ),
    ]
